---
- name: "Installing tools from APT (light install)"
  package:
    name:
      - jq
      - xxd
      - gdb
      - npm
      - xclip
      - bettercap
      - wafw00f
      - remmina
      - nuclei
      - feroxbuster
      - gobuster
      - rsyslog
      - xz-utils
      - httpx-toolkit
      - testssl.sh
      - iptables-persistent
    state: latest
  become: true
  become_method: sudo

- name: "Installing tools from APT (full install)"
  when: install_mode == 'full'
  package:
    name:
      - seclists
      - bloodhound
      - wine64
      - naabu
      - realtek-rtl88xxau-dkms
      - libpcap-dev
      - libreoffice
      - libkrb5-dev
      - krb5-config
    state: latest
  become: true
  become_method: sudo
