---
- name: "Installing tools from APT"
  package:
    name:
      - jq
      - xxd
      - gdb
      - npm
      - xclip
      - seclists
      - bettercap
      - wafw00f
      - remmina
      - nuclei
      - feroxbuster
      - gobuster
      - rsyslog
      - bloodhound
      - ufw
      - xz-utils
      - wine64
      - realtek-rtl88xxau-dkms
      - libpcap-dev
      - naabu
      - httpx-toolkit
      - testssl.sh
      - cargo
    state: latest
  become: true
  become_method: sudo

- name: "Setting date to France TZ"
  command: "timedatectl set-timezone Europe/Paris"
  become: true
  become_method: sudo

- name: Update local Database
  command: updatedb
  become: true
  become_method: sudo
