---
- name: "Installing tools from APT (light install)"
  package:
    name:
      - jq
      - xxd
      - gdb
      - npm
      - xclip
      - bettercap
      - wafw00f
      - remmina
      - nuclei
      - feroxbuster
      - gobuster
      - rsyslog
      - ufw
      - xz-utils
      - httpx-toolkit
      - testssl.sh
    state: latest
  become: true
  become_method: sudo

- name: "Installing tools from APT (full install)"
  when: install_mode == 'full'
  package:
    name:
      - seclists
      - bloodhound
      - wine64
      - naabu
      - realtek-rtl88xxau-dkms
      - libpcap-dev
      - cargo
    state: latest
  become: true
  become_method: sudo

- name: "Setting date to France TZ"
  command: "timedatectl set-timezone Europe/Paris"
  become: true
  become_method: sudo

- name: "Update local Database"
  command: updatedb
  become: true
  become_method: sudo
