---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'ldeep', url: 'git+https://github.com/franc-pentest/ldeep.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'coercer', url: 'git+https://github.com/p0dalirius/Coercer.git' }
    - { name: 'tldr', url: ''}
    - { name: 'sipvicious', url: 'git+https://github.com/EnableSecurity/sipvicious.git'}
    - { name: 'ApacheTomcatScanner', url: 'git+https://github.com/p0dalirius/ApacheTomcatScanner.git'}
    - { name: 'Crackmapexec', url: 'git+https://github.com/byt3bl33d3r/CrackMapExec.git'}
    - { name: 'vol', url: 'git+https://github.com/volatilityfoundation/volatility3.git'}
