---
- name: "Install GPG key for SublimeText"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: true
  become_method: sudo

- name: "Add repo to source.list.d"
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text.list
  become: true
  become_method: sudo

- name: "Installing subl from APT"
  apt:
    name: sublime-text
    state: latest
    update_cache: yes
  become: true
  become_method: sudo

- name: "Copy subl preferences"
  copy:
    src: "{{ role_path }}/files/Preferences.sublime-settings"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"

- name: "Copy subl bindings"
  copy:
    src: "{{ role_path }}/files/Default (Linux).sublime-keymap"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/Default (Linux).sublime-keymap"
