---
- name: "Check if Sublime Text binary exists"
  stat:
    path: /opt/sublime_text/sublime_text
  register: sublime_binary

- name: "Install GPG key for SublimeText"
  shell: "wget -O- https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/sublimehq-archive-keyring.gpg"
  when: sublime_binary.stat.exists == false
  become: true
  become_method: sudo

- name: "Add Sublime Text APT repository to sources list"
  shell: 'echo "deb [signed-by=/usr/share/keyrings/sublimehq-archive-keyring.gpg] https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
  when: sublime_binary.stat.exists == false
  become: true
  become_method: sudo

- name: "Uninstall Sublime Text (Debian/Ubuntu) if binary doesn't exist"
  when: sublime_binary.stat.exists == false
  apt:
    name: sublime-text
    state: absent
  become: true
  become_method: sudo

- name: "Installing SublimeText from APT"
  apt:
    name: sublime-text
    state: latest
    update_cache: yes
  become: true
  become_method: sudo

- name: "Check if User_preference path exists"
  stat:
    path: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/"
  register: user_preference_subl

- name: "Create directory for User preference"
  file:
    path: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/"
    state: directory
    mode: '0755'
  when: user_preference_subl.stat.exists == False

- name: "Copy subl preferences"
  copy:
    src: "{{ role_path }}/files/Preferences.sublime-settings"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"

- name: "Copy subl bindings"
  copy:
    src: "{{ role_path }}/files/Default (Linux).sublime-keymap"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text/Packages/User/Default (Linux).sublime-keymap"
