---
- name: Copy zedencrypt archive to the remote host
  copy:
    src: files/ZEDFREE-2023.2.Ubuntu.amd64.zip
    dest: /opt/ZEDFREE-2023.2.Ubuntu.amd64.zip
    mode: '0600'  # Set the appropriate permissions for the .deb file

- name: Unzip the zedencrypt archive
  unarchive:
    src: /opt/ZEDFREE-2023.2.Ubuntu.amd64.zip
    dest: /opt/zedencrypt  # Destination folder for the unzipped contents

- name: Install zedencrypt using dpkg
  apt:
    deb: "/opt/zedencrypt/Ubuntu 22.04/ZEDFREE-2023.2.Ubuntu22.04.amd64.deb"
    state: present
  register: install_result

- name: Check if the installation was successful
  debug:
    msg: "zedencrypt is installed successfully!"
  when: install_result is success

- name: Handle dependencies (if any)
  apt:
    autoremove: yes
  when: install_result is changed

