---
- name: "Update package cache (Debian/Ubuntu)"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo

- name: "Upgrade all packages (Debian/Ubuntu)"
  apt:
    upgrade: full
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - feh
      - ufw
      - neofetch
    state: latest
  become: true
  become_method: sudo
