---
- name: Install Regolith Certificates only if /etc/apt/sources.list.d/regolith.list does not exist
  ansible.builtin.stat:
    path: '/etc/apt/sources.list.d/regolith.list'
  register: regolith_installed

- name: Register Regolith public key
  ansible.builtin.shell:
    cmd: "wget -qO - https://regolith-desktop.org/regolith.key | gpg --dearmor | sudo dd of=/usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null"
  
- name: Add Regolith repository URL
  ansible.builtin.shell:
    cmd: "echo deb \"[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_0-{{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }}-amd64 {{ ansible_distribution_release|lower }} main\" | sudo tee /etc/apt/sources.list.d/regolith.list"
  
- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Regolith Desktop
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - regolith-desktop
    - regolith-session-flashback
    - regolith-look-lascaille

- name: Restart login manager
  ansible.builtin.service:
    name: lightdm  # Adjust the service name based on your system's login manager
    state: restarted

- name: Install i3 packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  loop: 
  - i3xrocks-battery
  - i3xrocks-bluetooth
  - i3xrocks-cpu-usage
  - i3xrocks-disk-capacity
  - i3xrocks-focused-window-name
  - i3xrocks-info
  - i3xrocks-memory
  - i3xrocks-microphone
  - i3xrocks-net-traffic
  - i3xrocks-rofication
  - i3xrocks-temp
  - i3xrocks-time
  - i3xrocks-updates
  - i3xrocks-volume
  - i3xrocks-wifi
  become: true
  when: not regolith_installed.stat.exists

- name: Append lines to the i3 config file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/config'
    block: '{{ i3_config_block }}'
    create: yes

- name: Append lines to the i3 Xresources file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/Xresources'
    block: '{{ i3_xresources_block }}'
    create: yes
