---
# vars file for install-tools
## Burp
burpsuite_extras_dir: "/usr/local/lib/BurpSuite"
burpsuite_extras_jars:
  jruby:
    jar: jruby-complete.jar
    url: https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.5.0/jruby-complete-9.4.5.0.jar
    checksum: sha256:89fad5ed6d815e05a9de5dece77e94810a81ddbf45a225358c82aa66f60857ba
  jython:
    jar: jython-standalone.jar
    url: https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.3/jython-standalone-2.7.3.jar
    checksum: sha256:da7f3d829b148bcfa86b059dc964e3a8556fedb021096c8db07e30c66faab9b4