---
# vars file for configure-i3
i3_config_block: |
    bindsym $mod+p exec flameshot gui
    bindsym $mod+s exec gnome-control-center sound
    bindsym $mod+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --off
    bindsym $mod+Shift+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --auto

i3_xresources_block: |
    gtk.font_name: Nerd Font Mono 10
    regolith.wallpaper.file: /opt/lalubuntu/screens/wallpaper.png
    regolith.wallpaper.options: stretched
